// Thumbnail blocks exactly as PrusaSlicer, OrcaSlicer and Bambu Studio write them: base64 split into 78-character comment lines.
export function thumbnailBlock(image: Buffer, width: number, height: number, tag = "thumbnail"): string {
  const encoded = image.toString("base64");
  const rows = encoded.match(/.{1,78}/g) ?? [];
  return [";", `; ${tag} begin ${width}x${height} ${encoded.length}`, ...rows.map((row) => `; ${row}`), `; ${tag} end`, ";"].join("\n");
}

export function gcode(...headerBlocks: string[]): string {
  return [
    "; generated by PrusaSlicer 2.9.0 on 2026-09-29 at 12:00:00 UTC",
    "",
    ...headerBlocks,
    "",
    "; external perimeters extrusion width = 0.45mm",
    "M73 P0 R12",
    "M107",
    "G90",
    "G1 Z0.2 F720",
    "G1 X10 Y10 E0.5",
    ""
  ].join("\n");
}
